# Generated by Django 4.2.8 on 2024-01-03 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "creator",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contributed_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("winnings", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wager",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, null=True)),
                ("description", models.TextField(null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("stake", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("winning_percentage", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("number_of_winners", models.PositiveIntegerField(null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("participants", models.ManyToManyField(related_name="wagers", to="wagers.participant")),
            ],
        ),
        migrations.CreateModel(
            name="WagerInvitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=10)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wagers.event")),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wager_invitations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wager_invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wager Invitation",
                "verbose_name_plural": "Wager Invitations",
            },
        ),
        migrations.CreateModel(
            name="WagerRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("rejected", models.DateTimeField(blank=True, null=True)),
                ("viewed", models.DateTimeField(blank=True, null=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wager_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wager_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("wager", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wagers.wager")),
            ],
            options={
                "verbose_name": "Wager Request",
                "verbose_name_plural": "Wager Requests",
                "unique_together": {("from_user", "to_user")},
            },
        ),
    ]
