# Generated by Django 4.2.8 on 2024-01-07 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WagerParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contributed_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("winnings", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("is_creator", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Participant",
        ),
        migrations.AlterField(
            model_name="wager",
            name="participants",
            field=models.ManyToManyField(related_name="wagers", to="wagers.wagerparticipant"),
        ),
    ]
