# Generated by Django 4.2.8 on 2024-02-10 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagers", "0002_wagerparticipant_delete_participant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wagerparticipant",
            name="user",
        ),
        migrations.AddField(
            model_name="wagerparticipant",
            name="participant",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="wagerparticipant",
            name="wager",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="wagers.wager"
            ),
        ),
        migrations.AlterField(
            model_name="wager",
            name="participants",
            field=models.ManyToManyField(related_name="wagers", to=settings.AUTH_USER_MODEL),
        ),
    ]
