# Generated by Django 4.2.8 on 2024-02-14 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagers", "0005_remove_wager_participants_wager_participant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wagerparticipant",
            old_name="participant",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="wager",
            name="participant",
        ),
        migrations.RemoveField(
            model_name="wager",
            name="stake",
        ),
        migrations.AddField(
            model_name="wager",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="wagers_participated",
                through="wagers.WagerParticipant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wagerparticipant",
            name="stake",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
