# Generated by Django 4.2.8 on 2024-02-16 00:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagers", "0006_rename_participant_wagerparticipant_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wagerparticipant",
            old_name="user",
            new_name="participant",
        ),
    ]
